name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - '*'

jobs:
  lint:
    name: Check code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          java-package: jdk
          cache: 'maven'
      - name: spotless:check
        run: mvn --batch-mode --no-transfer-progress spotless:check

  test:
    name: test ${{ matrix.os }} jdk${{ matrix.java }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        java: [ 17, 21 ]
        include:
          - os: windows-latest
            java: 21
          - os: macos-latest
            java: 21
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          java-package: jdk
          cache: 'maven'

      - name: Test
        run: mvn --batch-mode --no-transfer-progress test